// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPrHbXXRx0yqDgRtx1gj7M47BDVvO4nPA',
    appId: '1:804158452023:web:7f2ace09a2dc3c5da36ab2',
    messagingSenderId: '804158452023',
    projectId: 'avahan-dev',
    authDomain: 'avahan-dev.firebaseapp.com',
    storageBucket: 'avahan-dev.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2HvqY0vGYLYeK4xtMgPhg1J_t05fzPak',
    appId: '1:804158452023:android:91a1ba64fb8e04b6a36ab2',
    messagingSenderId: '804158452023',
    projectId: 'avahan-dev',
    storageBucket: 'avahan-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlbEGjl40efk-t8-eqVtJq4KoOlSZpVsY',
    appId: '1:804158452023:ios:25479533577679bfa36ab2',
    messagingSenderId: '804158452023',
    projectId: 'avahan-dev',
    storageBucket: 'avahan-dev.appspot.com',
    androidClientId:
        '804158452023-81rj8946k4evbpk9080t3hn42p8tvmum.apps.googleusercontent.com',
    iosBundleId: 'com.avahan.ios',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlbEGjl40efk-t8-eqVtJq4KoOlSZpVsY',
    appId: '1:804158452023:ios:3207e0e66dfb6731a36ab2',
    messagingSenderId: '804158452023',
    projectId: 'avahan-dev',
    storageBucket: 'avahan-dev.appspot.com',
    androidClientId:
        '804158452023-81rj8946k4evbpk9080t3hn42p8tvmum.apps.googleusercontent.com',
    iosBundleId: 'com.avahan.avahan.RunnerTests',
  );
}
